#!/bin/bash -x

if [ $# -eq 0 ]; then
  echo "usage $0 clusterip storageip"
  exit 999
fi

clusterip=$1
storageip=$2

name=`curl -kX GET -H "Authorization: Basic YWRtaW46bnV0YW5peC80dQ==" -H "Cache-Control: no-cache" -H "Postman-Token: 9473a44b-bf89-5c2b-6536-7f4512252a38" "https://10.68.69.102:9440/api/nutanix/v2.0/cluster/" 2>/dev/null  |jq -r '.name'`
#id=`curl -kX GET -H "Authorization: Basic YWRtaW46bnV0YW5peC80dQ==" -H "Cache-Control: no-cache" -H "Postman-Token: 9473a44b-bf89-5c2b-6536-7f4512252a38" "https://10.68.69.102:9440/api/nutanix/v2.0/cluster/" 2>/dev/null  |jq -r '.id'`
#uuid=`curl -kX GET -H "Authorization: Basic YWRtaW46bnV0YW5peC80dQ==" -H "Cache-Control: no-cache" -H "Postman-Token: 9473a44b-bf89-5c2b-6536-7f4512252a38" "https://10.68.69.102:9440/api/nutanix/v2.0/cluster/" 2>/dev/null  |jq -r '.uuid'`

cat api-updatestorageip |sed -e "s/namestring/$name/" -e  "s/clusterstring/$clusterip/" -e "s/datastring/$storageip/" > run-updatestorageip
chmod a+x run-updatestorageip

./run-updatestorageip

exit

curl -kX PUT -H "Authorization: Basic YWRtaW46bnV0YW5peC80dQ==" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -u admin/nutanix/4u -d '{
  "name": "namestring",
  "cluster_external_data_services_i_p_address": "clusterstring",
  "cluster_external_i_p_address": "datastring"
}' "https://10.68.69.102:9440/api/nutanix/v2.0/cluster/"


